### ISSUE TITLE
Tratamiento de la semilla 

### ISSUE THREAD

**Issue by jodavelo** [CIAT-DAPA/aeps_platform_forms#100]
- •	Revise unidades de dosificación de tratamiento de semilla con Luciano. 
- •	Para el costo del tratamiento reordenar: Producto utilizado / Unidad de la dosis / Dosis / Cantidad Utilizada/ Unidad del costo “unitario” del producto / Costo del producto. 
- •	Cuando se seleccionan dos tratamientos de semilla, en la segunda aparecio un mensaje de error y no permitia ingresar mas productos.

**Comment by j-river1** [comment]
Se pregunto por whatsap. Y el modulo de costos queda asi:

1. Cantidad de producto por hectarea
2. Unidad del producto
3. Costo del producto en la unidad reportada
4. Costo unitario del producto
5. Tipo de costos. Detallado (maquinaria, combustible, operador) o total

**Comment by j-river1** [comment]
Las unidad de dosis quedaron como:

kg/ha, l/ha, gr/ha, ml/ha
