### ISSUE TITLE
Nivelación

### ISSUE THREAD

**Issue by bigdataciat** [CIAT-DAPA/aeps_platform_forms#11]
Poner opciones para nivelación de terreno:

1. nivelado en seco (rufa)
2. Nivelado con lacer
3. nivelado en suelo batido

**Comment by stevensotelo** [comment]
@bigdataciat Esa información es del lote, del evento productivo o donde?

**Comment by bigdataciat** [comment]
Es probable que un lote le hagan nivelación laser una vez por varios eventos productivos. pero el nivelado en seco o en suelo batido, lo hacen antes de todas las siembras así que los dejaría asociados al evento productivo.
