### ISSUE TITLE
Información del agricultor

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/aeps_platform_forms#146]
- [ ] Se debe revisar la sección de distritos, que al seleccionar un distrito, vuelve a solicitar información de otro distrito:

![bc0fa161-d6fc-45df-acd2-c7ebf1780d35](https://user-images.githubusercontent.com/4921829/90039470-48046080-dc8c-11ea-9b43-eef14346876a.jpg)
![d480f28c-491f-42ca-b730-7910df92e2ea](https://user-images.githubusercontent.com/4921829/90039476-49358d80-dc8c-11ea-8fa7-218fa557c9ee.jpg)

- [ ] El campo celular no debe permitir letras, debe permitir solamente formatos de número celular

![7bec4228-dc5d-4327-a45e-288237855835](https://user-images.githubusercontent.com/4921829/90041968-a4b54a80-dc8f-11ea-8add-26d3662fb734.jpg)

**Comment by j-river1** [comment]
Se dejo así porque era más sencillo implementarlo en xlsform porque en cascada en mas dificl colocar un otro. Pero la pregunta dice que si no la encuentra el distrito escribirla aqui.

**Comment by stevensotelo** [comment]
- [ ] Se debe permitir tíldes en nombres y apellidos

![image](https://user-images.githubusercontent.com/4921829/90140264-18faf700-dd3f-11ea-9f04-5703480ae5f3.png)

**Comment by stevensotelo** [comment]
- [ ] En la pregunta de número de idnetificación quitar el texto que dice que solo permite números, ya que tambien permite textos

**Comment by stevensotelo** [comment]
Ajustar texto de esta pregunta

![image](https://user-images.githubusercontent.com/4921829/90140418-5a8ba200-dd3f-11ea-9a3c-eb3461acfa01.png)

**Comment by stevensotelo** [comment]
Ajustar texto

- [ ] Palabra diligenciar

![image](https://user-images.githubusercontent.com/4921829/90140581-945ca880-dd3f-11ea-8855-f4f3bb87a231.png)
