### ISSUE TITLE
Que es código de finca?

### ISSUE THREAD

**Issue by hdorado** [CIAT-DAPA/aeps_platform_forms#18]

**Comment by stevensotelo** [comment]
Hola @hdorado 

Este campo es para poder precargar los datos de la finca. Este campo se debe diligenciar si se conoce el código de la finca en el archivo de precarga de información creado, en el caso de conocerce se diligencia y ODK llenará los datos faltantes de la finca; en el caso contrario, el usuario deberá diligenciar los datos
