### ISSUE TITLE
Si alguien coloca algunos datos de ciclo en intermedio y luego en avanzado es posible?

### ISSUE THREAD

**Issue by hdorado** [CIAT-DAPA/aeps_platform_forms#25]

**Comment by stevensotelo** [comment]
@hdorado 

Si, es posible en este momento, consideras que no es buena idea?

Lo que queremos es obtener la mayor información que sea posible colectar de un evento productivo, por esa razón cada sección tiene sus tres niveles. La idea es que la persona que colecta la información pueda ingresar los datos que tiene a su disposición
