### ISSUE TITLE
Metodo de siembra

### ISSUE THREAD

**Issue by bigdataciat** [CIAT-DAPA/aeps_platform_forms#4]
La mayoría se las siembras son por transplante, eso requiere entonces preguntar con fecha de siembra y por fecha de transplante, en este caso con las opciones 1. transplante manual 2 transplante con máquina.

Para siembra en lote definitivo las opciones son: 1. siembra directa (Tapadura), 2 Siembra mecanizada semilla seca. 3. boleo de semilla pregerminada.

**Comment by stevensotelo** [comment]
Se ha ajustado el formulario con la nueva pregunta, sin embargo no se elimino la pregunta inicial cccc1a3
