### ISSUE TITLE
Agregar localidades en agricultor y asistente tecnico

### ISSUE THREAD

**Issue by jodavelo** [CIAT-DAPA/aeps_platform_forms#45]
Incluir pais uruguay en y nicaragua con sus repectivas opciones de estados y municipios

**Comment by j-river1** [comment]
Falta Rio Grande del Sur. Lo menciono Luciano en la grabación.

**Comment by j-river1** [comment]
Se puede colocar. **Pais**: Brasil. **Departamento**: Rio grande del sur. **Ciudad:**
Región Centro Occidental
Región Centro Oriental
Región Metropolitana de Porto Alegre
Región Nordeste
Región Noroeste
Región Sudeste
Región Sudoeste
