### ISSUE TITLE
Preguntar por clasificacion del lote

### ISSUE THREAD

**Issue by jodavelo** [CIAT-DAPA/aeps_platform_forms#49]
Agregar opciones para poder escoger la clasificacion del lote, las opciones son:
 ```
        - parsela demostrativa, numero de hectáreas

	- pásela testigo, numero de hectáreas

	- lote comercial, numero de hectáreas
```
Nota: se debe añadir antes de datos del suelo

**Comment by j-river1** [comment]
Hay dos errores de ortografía.  El primero, no es clacificación sino  clasificiación. Y el segundo, no es parsela sino parcela.
