### ISSUE TITLE
Fertilización

### ISSUE THREAD

**Issue by bigdataciat** [CIAT-DAPA/aeps_platform_forms#5]
Sugieren que profundicemos un poco mas. preguntando por la fertilización en dos épocas: Macollo (fecha) y Floración (fecha).

se requeriría además cantidad de N / P / K

**Comment by stevensotelo** [comment]
@bigdataciat las fechas que se requieren (macollo y floración) son de que nivel: básico, intermedio o avanzado?

**Comment by bigdataciat** [comment]
Pienso que básico. realmente no son todos los estados fenológicos que pudieran ser.
