### ISSUE TITLE
Riego

### ISSUE THREAD

**Issue by bigdataciat** [CIAT-DAPA/aeps_platform_forms#6]
Todos usan riego.  discutíamos mejor poner la opción de medir lámina de agua, darle una regla al tomador de datos, y que mida la lámina en tres puntos del lote. junto con el área del lote poder calcular volumen de agua.  

Además preguntar a partir de que día luego de transplante se mantiene la lámina de agua.

**Comment by stevensotelo** [comment]
Se adiciono en nivel avanzado la nueva pregunta sobre lámina de agua commit cccc1a3
