### ISSUE TITLE
Las fechas del cultivo

### ISSUE THREAD

**Issue by j-river1** [CIAT-DAPA/aeps_platform_forms#89]
Falta los compos de fecha siembra, fecha emergencia y poblacion plantas

**Comment by jodavelo** [comment]
Los campos fecha de emergencia y poblacion de plantas, aparecen segun seleccionen el sistema de cultivo.

**Comment by j-river1** [comment]
Si, las fechas de emergencia y población de plantas aparecen pero no la fecha de siembra, la agrego en el grupo de preguntas, Variedad.
