### ISSUE TITLE
Costo del valor de la finca que le pertenece al agricultor

### ISSUE THREAD

**Issue by jodavelo** [CIAT-DAPA/aeps_platform_forms#93]
- Permite negativo
- ¿Es relevante preguntar el costo de la finca o solos nos interesa el costo de arrendamiento del área cultivada con arroz? 
- Que significa esta pregunta, las fincas pueden costar millones y no se cual es el valor de tener esta informacion.

**Comment by stevensotelo** [comment]
Se consulta con el grupo y se decide dejar el grupo de preguntas 1: Propiedad de la finca, de la siguiente manera:

- Porcentaje del lote que le pertenece al agricultor
- Porcentaje del lote que tiene arrendado el agricultor
- Costo del arriendo del lote (moneda local/ha)
- Porcentaje de otra forma propiedad  
- Ingrese la otra forma de propiedad de la finca
- Forma de pago de la otra forma de propiedad Permitir texto y números

las tres primeras obligatorias, 4 opcional , 5 y 6 depende si hay valor en la 4

Validar que el total del porcentaje sea 100 entre todas las opciones
